name: Build
on: 
  workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository_owner == github.actor  # avoid forks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for git tags & history

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install
        run: npm i
      - name: Build
        run: npm run-script build
      
